"""add initial models

Revision ID: 18b9d421fbde
Revises: 
Create Date: 2022-03-19 12:36:16.067795

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "18b9d421fbde"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stats",
        sa.Column("user", sa.BigInteger(), nullable=False),
        sa.Column("count", sa.BigInteger(), nullable=True),
        sa.PrimaryKeyConstraint("user"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("stats")
    # ### end Alembic commands ###
