"""add user name

Revision ID: 260284d8c6c8
Revises: 18b9d421fbde
Create Date: 2022-03-19 12:38:52.473919

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "260284d8c6c8"
down_revision = "18b9d421fbde"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("stats", sa.Column("name", sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("stats", "name")
    # ### end Alembic commands ###
