"""add daily/weekly claims

Revision ID: 73c4380fcc05
Revises: 260284d8c6c8
Create Date: 2022-03-19 15:40:59.851310

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "73c4380fcc05"
down_revision = "260284d8c6c8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("stats", sa.Column("last_daily", sa.DateTime(), nullable=True))
    op.add_column("stats", sa.Column("last_weekly", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("stats", "last_weekly")
    op.drop_column("stats", "last_daily")
    # ### end Alembic commands ###
