name: Build and Deploy
on:
  push:
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Fetch metadata
      id: metadata
      uses: docker/metadata-action@v4
      with:
        images: ghcr.io/ass-a-service/ajobot
    - name: build and push
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: ${{ steps.metadata.outputs.tags }}
        labels: ${{ steps.metadata.outputs.labels }}
