name: Build and Deploy
on:
  push:
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: crazy-max/ghaction-docker-meta@v1
      id: docker_meta
      with: 
        images: ghcr.io/ass-a-service/ajobot
    - name: build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ steps.docker_meta.outputs.tags }}
        labels: ${{ steps.docker_meta.outputs.labels }}
  deploy:
    name: deploy to cluster
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: deploy to cluster
      uses: steebchen/kubectl@v2.0.0
      with:
        config: ${{ secrets.KUBE_CONFIG_DATA }}
        command: set image --record -n ajobot deployment/ajobot ajobot=ghcr.io/ass-a-service/ajobot:${{github.ref_name}}
    - name: verify deployment
      uses: steebchen/kubectl@v2.0.0
      with:
        config: ${{ secrets.KUBE_CONFIG_DATA }}
        command: rollout status deployment/ajobot -n ajobot